spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: courseMicroservice
          uri: http://localhost:8082/
          predicates:
            - Path=/v1/admin/course/**
        - id: authMicroservice
          uri: http://localhost:8083/
          predicates:
            - Path=/login


server:
  port: 8080
  servlet:
    context-path: /gateway
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true
