
#spring config
server:
  port: 8083


#mysql
spring:
  application:
    name: auth
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/devdojo
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true


#eureka-client
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true